### ISSUE TITLE
Incorrect spacing with scaled slash

### ISSUE THREAD

**Issue by atxy-blip** [AlphaZTX/fixdif#7]
I tend to scale up the slash symbol a little bit in cases when I need to typeset tall denominators. However, with `\big` command inserted, `\d` behaves differently from documentation with additional space before it.
<img width="119" alt="image" src="https://github.com/AlphaZTX/fixdif/assets/63113546/4e50d0f8-15e9-4901-a99c-ca920259b317">

```tex
\documentclass{article}
\usepackage{unicode-math, fixdif}

\begin{document}
\def\foo{\d \hat{V}}
\[
    \begin{array}{l}
    \foo \big/\symup{d} t\\
    \foo \big/\d t\\
    \foo /\d t\\
    \end{array}
\]
\end{document}
```

**Comment by AlphaZTX** [comment]
Do NOT use `\big`, use `\bigl` instead.

**Comment by AlphaZTX** [comment]
By the way, it's no need to pursue the absolute correctness in “inputing form” in my opinion. `fixdif` just offers a simpler method to input differential operators.

**YOU** are the user of LaTeX, the controller of TeX. The final typesetting result has better determined on **YOU** but not `fixdif`. This issue is a good example to illustrate this statement. As for some OpenType math fonts, the right bounds of glyph “mathematical italic capital v” are usually not negative (or not that negative). This causes the optical skip between “mathematical italic capital v” and slash looks bigger than the optical skip between slash and “d”. If you want them to look more even, setting the skips manually is a better choice for you, though it may not look “semantic” enough in your source code.
